### ISSUE TITLE
Field of view is `NaN` on macOS

### ISSUE THREAD

**Issue by olokobayusuf** [natmlx/NatDevice#10]

**Comment by olokobayusuf** [comment]
Not reproducible.

**Comment by joensaar** [comment]
I must have remembered incorrectly when I reported this. It's actually 0 instead of NaN in the Unity Editor.
Debug.Log on CameraDevice.fieldOfView.width and CameraDevice.fieldOfView.height gives 0.

For me this isn't a big problem at all, but thought you should know.

<img width="698" alt="Screenshot 2022-11-01 at 15 19 10" src="https://user-images.githubusercontent.com/43815747/199243916-0a694599-0db4-40fc-babc-962765e51234.png">

**Comment by olokobayusuf** [comment]
@joensaar this is expected behaviour on macOS. [This information is not exposed in the macOS SDK](https://developer.apple.com/documentation/avfoundation/avcapturedeviceformat/1624569-videofieldofview?language=objc).
